CREATE TABLE produtos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    preco NUMBER,
    nome VARCHAR2,
    PRIMARY KEY(id)
);

CREATE TABLE funcionarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2,
    salario_base NUMBER(10,2),
    cpf VARCHAR2,
    PRIMARY KEY(id)
)

CREATE TABLE niveis_fidelidade (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2,
    PRIMARY KEY(id)
);

CREATE TABLE vendas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    produto_id NUMBER,
    vendedor_id NUMBER,
    FOREIGN KEY(produto_id) REFERENCES produtos.id,
    FOREIGN KEY(vendedor_id) REFERENCES funcionarios.id,
    PRIMARY KEY(id)    
);