CREATE TABLE produtos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    preco NUMBER,
    nome VARCHAR2(128),
    PRIMARY KEY(id)
);

CREATE TABLE funcionarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(128),
    salario_base NUMBER(10,2),
    cpf VARCHAR2(14),
    PRIMARY KEY(id)
);

CREATE TABLE niveis_fidelidade (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(128),
    PRIMARY KEY(id)
);

CREATE TABLE enderecos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    logradouro VARCHAR2(128),
    numero NUMBER,
    estado VARCHAR2(2),
    cidade VARCHAR2(128),
    PRIMARY KEY(id)
);

CREATE TABLE clientes_fidelizados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(128),
    data_nascimento DATE,
    niveis_fidelidade_id NUMBER,
    tempo_fidelizacao DATE,
    bonus_fidelidade NUMBER,
    endereco_id NUMBER,
    PRIMARY KEY(id),
    FOREIGN KEY(niveis_fidelidade_id) REFERENCES niveis_fidelidade(id),
    FOREIGN KEY(endereco_id) REFERENCES enderecos(id)
);

CREATE TABLE vendas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    produto_id NUMBER,
    vendedor_id NUMBER,
    FOREIGN KEY(produto_id) REFERENCES produtos(id),
    FOREIGN KEY(vendedor_id) REFERENCES funcionarios(id),
    PRIMARY KEY(id)    
);

CREATE TABLE gerente (
    funcionario_id NUMBER,
    bonus NUMBER,
    PRIMARY KEY(funcionario_id),
    FOREIGN KEY(funcionario_id) REFERENCES funcionarios(id)
);